Datastructure - List

In [27]:
my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]  # Creating a list

In [29]:
print(my_list) # Accessing All elements of the list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [31]:
print(my_list[0]) # Accessing the element at index position 0 (zero)

0


In [33]:
my_list.append(10) # Appending / Adding an element to the list, note: Append add the element to end position on the list 
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [35]:
my_list.remove(10) # removing the specified value from the list
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [37]:
print(my_list[1:4]) # Slicing the list (Starting Index : Ending Index (excluded))

[1, 2, 3]


Datastructure - Tuple

In [42]:
my_tuple = (10, 11, 12, 13, 14, 15) # Creating a tuple

In [46]:
print(my_tuple) # printing all elements in a tuple

(10, 11, 12, 13, 14, 15)


In [48]:
print(my_tuple[0]) # printing the element at index position 0

10


In [50]:
my_tuple[1] = 12

TypeError: 'tuple' object does not support item assignment

In [54]:
print(my_tuple[1:4]) # slicing element from start index 1 to end index 4 (excluded)

(11, 12, 13)


Datastructure - Dictionary

In [57]:
my_dict = {
    'Name' : 'Harry Potter',
    'Age' : 25,
    'Job' : 'Wizard',
    'City' : 'Hogwarts'
}

In [59]:
my_dict['email'] =  'harrypoter@hogwarts.com'
print(my_dict)

{'Name': 'Harry Potter', 'Age': 25, 'Job': 'Wizard', 'City': 'Hogwarts', 'email': 'harrypoter@hogwarts.com'}


In [61]:
del my_dict['email']
print(my_dict)

{'Name': 'Harry Potter', 'Age': 25, 'Job': 'Wizard', 'City': 'Hogwarts'}


Datastructures - Set

In [64]:
my_set = {1, 2, 3, 4, 5}

In [66]:
my_set.add(6)
print(my_set)

{1, 2, 3, 4, 5, 6}


In [68]:
my_set.remove(3)
print(my_set)

{1, 2, 4, 5, 6}


In [72]:
another_set = {3, 4, 5, 6, 7, 8, 9, 10}
print(my_set & another_set)

{4, 5, 6}


In [74]:
print(my_set | another_set)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [76]:
print(my_set - another_set)

{1, 2}


In [80]:
print(another_set - my_set)

{3, 7, 8, 9, 10}


In [86]:
list_of_tuples = [('Name', 'Ron Weasley'), ('Age', 25), ('City', 'London')]
my_dict2 = dict(list_of_tuples)
print(my_dict2)

{'Name': 'Ron Weasley', 'Age': 25, 'City': 'London'}


In [94]:
students = [('Harry', (81, 90, 87)), ('Ron', (80, 91, 88)), ('Hermione', (90, 91, 92))]
students_dict = {names : grades for names, grades in students}
print(students_dict)

{'Harry': (81, 90, 87), 'Ron': (80, 91, 88), 'Hermione': (90, 91, 92)}


In [96]:
dict1 = {'Name' : 'Alice', 'Age' : 25 }
dict2 = {'City' : 'New York', 'Email' : 'alice@example.com'}

dict1.update(dict2)
print(dict1)

{'Name': 'Alice', 'Age': 25, 'City': 'New York', 'Email': 'alice@example.com'}


In [98]:
merged_dict = {**dict1, **dict2}
print(merged_dict)

{'Name': 'Alice', 'Age': 25, 'City': 'New York', 'Email': 'alice@example.com'}


In [107]:
print('List at begining -', my_list)
my_list.reverse()
print('After list reverse fn -', my_list)

List at begining - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
After list reverse fn - [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [109]:
sorted_list = sorted(my_list)
print(sorted_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [111]:
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)
concatenated_tuple = tuple1 + tuple2
print(concatenated_tuple)

(1, 2, 3, 4, 5, 6)


Datastructures - Array

In [4]:
import numpy as np 
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Matrix : {matrix}")

Matrix : [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
transposed_matrix = matrix.T
print(f"Transposed Matrix: {transposed_matrix}")

Transposed Matrix: [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [6]:
product = np.dot(matrix, transposed_matrix)
print(f"Product : {product}")

Product : [[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


______________________________________________________________________________________

In [7]:
fruits = ["apple", "banana", "apple", "orange", "apple", "kiwi", "kiwi" ]

In [8]:
fruits.count("apple")

3

In [9]:
fruits.count("banana")

1

In [10]:
fruits.count("kiwi")

2

In [11]:
fruit_set = set(fruits)

In [24]:
for item in fruit_set:
    print(f"{item} : {fruits.count(item)}")

apple : 3
banana : 1
orange : 1
kiwi : 2


Practice

Lists:

Question - Appending and Removing Elements: Create an empty list called my_list. Appendthe numbers 1, 2, and 3 to my_list. Then remove the number 2 from the list.

In [142]:
my_list = []
print(type(my_list))
my_list.append(1)
my_list.append(2)
my_list.append(3)

print(f'The initial list \'my_list\' - {my_list}')

my_list.remove(2)
print(f'The list \'my_list\' after remove fn- {my_list}')

<class 'list'>
The initial list 'my_list' - [1, 2, 3]
The list 'my_list' after remove fn- [1, 3]


Question- Accessing Elements: Create a list called fruits containing the strings "apple","banana", "cherry", "date". Print the second element of the list.

In [120]:
fruits = ["apple", "banana", "cherry", "date"]
print(f'Second element in fruits list is : {fruits[1]}') # list index starts from 0, so second elemnt will be at position 1

Second element in fruits list is : banana


Question- Slicing: Create a list called numbers containing the numbers from 1 to 10. Print aslice of the list containing elements from the third element to the sixth element.

In [129]:
numbers  = list(range(1,11))
print(f'list of numbers 1 - 10 : {numbers}')
print(f'Slice from the list 3rd to 6th element - {numbers[3:7]}')

list of numbers 1 - 10 : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Slice from the list 3rd to 6th element - [4, 5, 6, 7]


_____________________________________________________________________________________

Sets

Question - Adding and Removing Elements: Create an empty set called my_set. Add thenumbers 1, 2, and 3 to my_set. Then remove the number 2 from the set.

In [140]:
my_set = set()
print(type(my_set))
my_set.add(1)
my_set.add(2)
my_set.add(3)
print(f'Initial set - {my_set}')
my_set.remove(2)
print(f'The set \'my_set\' after remove fn- {my_set}')

<class 'set'>
Initial set - {1, 2, 3}
The set 'my_set' after remove fn- {1, 3}


Question - Operations: Create two sets called set1 and set2, each containing a fewnumbers. Print the union, intersection, and difference of the two sets.

In [153]:
set1 = set([24,59,68,87,62,24,38,66])
set2 = set([88,59,67,87,54,42,38,16])

print(f'Union of set1 and set2 - {set1 | set2}')
print(f'Intersection of set1 and set2 - {set1 & set2}')
print(f'Difference of set1 and set2 - {set1 - set2}')
print(f'Difference of set2 and set1 - {set2 - set1}')

Union of set1 and set2 - {66, 67, 68, 38, 88, 42, 16, 54, 87, 24, 59, 62}
Intersection of set1 and set2 - {59, 38, 87}
Difference of set1 and set2 - {24, 66, 68, 62}
Difference of set2 and set1 - {67, 42, 16, 54, 88}


________________________________________________________________________________

Tuples

Question - Accessing Elements: Create a tuple called coordinates containing the latitudeand longitude of a location (e.g., (40.7128, -74.0060) for New York City). Print the latitudeand longitude separately.

In [163]:
coordinates = ('New York', (40.7128, -74.0060))
print(f'{coordinates[0]} - Latitude is : {coordinates[1][0]}')
print(f'{coordinates[0]} - Longitude is : {coordinates[1][1]}')

New York - Latitude is : 40.7128
New York - Longitude is : -74.006


Question - Packing and Unpacking: Create a tuple called person containing informationabout a person, such as their name, age, and city. Then unpack the tuple into individualvariables.

In [168]:
person = ('Harry Potter', 25, 'Hogwarts')
name, age, city = person
print(f'Name : {name}')
print(f'Age : {age}')
print(f'City : {city}')

Name : Harry Potter
Age : 25
City : Hogwarts


____End of file____