#Numpy

In [2]:
import numpy as np

# Creating Array

In [3]:
#1D Array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
# 2D Array
arr_2D = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr_2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
#Zeros Array
arr_zero = np.zeros((3, 3))
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
#Ones Array
arr_one = np.ones((3, 3))
print(arr_one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
#Range
range = np.arange(0, 11, 2)
print(range)

[ 0  2  4  6  8 10]


In [13]:
#Linspace
linspace_arr = np.linspace(0, 1, 5)
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


# Array Properties

In [15]:
# Shape
print(arr_2D.shape)

# Number of dimension
print(arr_2D.ndim)

# Total Number of elements
print(arr_2D.size)

# Data Type
print(arr_2D.dtype)

(2, 5)
2
10
int32


# Array Indexing and Slicing


In [17]:
# Indexing ( row 0 and column 1)
print(arr_2D[0, 1])

# Slice
print(arr_2D[0, :]) #rows

print(arr_2D[:, 1]) #columns

2
[1 2 3 4 5]
[2 7]


# Reshaping and Manipulating

In [19]:
# Reshape 1D to 2D
reshaped = np.reshape(arr, (5, 1))
print(reshaped)

# Flatten 2D to 1D
flattened = arr_2D.flatten()
print(flattened)

#Concatenation and Split
concat = np.concatenate((arr, flattened), axis=0)
print(concat)

split = np.array_split(concat, 3)
print(split)

[[1]
 [2]
 [3]
 [4]
 [5]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  1  2  3  4  5  6  7  8  9 10]
[array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


# Logical Operations


In [21]:
#Boolean Indexing
bool_arr = arr>3
print(bool_arr)

filtered = arr[bool_arr]
print(filtered)

[False False False  True  True]
[4 5]


# Hands-On Exercises

1. Create a 3x3 identity matrix using NumPy.

2. Generate a 2D array with random integers and compute the row-wise sum.

3. Create a 1D array with 10 evenly spaced values between 0 and 100.

4. Perform element-wise addition, multiplication, and division on two random arrays of size 4x4.

5. Find the maximum value and its index in a randomly generated array.

In [23]:
#Create a 3x3 identity matrix using NumPy.
identity_matrix = np.eye(3)
print(f"Identity Matrix: \n")
print(identity_matrix)


Identity Matrix: 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
#Generate a 2D array with random integers and compute the row-wise sum.
rand_arr = np.random.randint(1,20, size=(3, 3))
i = 0
for row in rand_arr:
    print(f"Row Number {i}: {row}") 
    i += 1
print(f"\nRow Sum : {rand_arr.sum(axis =1)}")

Row Number 0: [19  9  5]
Row Number 1: [12 11 10]
Row Number 2: [17 18 14]

Row Sum : [33 33 49]


In [58]:
#Create a 1D array with 10 evenly spaced values between 0 and 100.
arr_1D = np.arange(0,100, 10)
print(f"1D Array with 10 evenly spaced values between 0 and 100 :\n")
print(arr_1D)

1D Array with 10 evenly spaced values between 0 and 100 :

[ 0 10 20 30 40 50 60 70 80 90]


In [79]:
#Perform element-wise addition, multiplication, and division on two random arrays of size 4x4.
rand_arr1 = np.random.randint(10,30, size=(4, 4))
rand_arr2 = np.random.randint(30,40, size=(4, 4))

print("\nRandom Array 1:\n", rand_arr1)
print("\nRandom Array 2:\n", rand_arr2)

#element-wise addition
elem_addition = rand_arr1 + rand_arr2
print(f"\nResult of element-wise addition:\n {elem_addition}")

#element-wise multiplication
elem_multiplication = np.dot(rand_arr1, rand_arr2)
print(f"\nResult of element-wise multiplcation:\n {elem_multiplication}")

#element-wise division
elem_division = np.divide(rand_arr1, rand_arr2)
print(f"\nResult of element-wise division:\n {elem_division}")


Random Array 1:
 [[14 23 11 19]
 [18 28 12 14]
 [11 28 16 27]
 [21 14 13 21]]

Random Array 2:
 [[35 33 31 32]
 [39 39 32 38]
 [36 39 36 33]
 [32 35 33 38]]

Result of element-wise addition:
 [[49 56 42 51]
 [57 67 44 52]
 [47 67 52 60]
 [53 49 46 59]]

Result of element-wise multiplcation:
 [[2391 2453 2193 2407]
 [2602 2644 2348 2568]
 [2917 3024 2704 2970]
 [2421 2481 2260 2431]]

Result of element-wise division:
 [[0.4        0.6969697  0.35483871 0.59375   ]
 [0.46153846 0.71794872 0.375      0.36842105]
 [0.30555556 0.71794872 0.44444444 0.81818182]
 [0.65625    0.4        0.39393939 0.55263158]]


In [81]:
rand_arr3 = np.random.randint(0, 500, size=(4, 4))

# Find the maximum value in the array
max_value = rand_arr3.max()

# Find the index of the maximum value
max_index = np.unravel_index(np.argmax(rand_arr3), rand_arr3.shape)

print("Random Array:\n", rand_arr3)
print("Maximum Value:", max_value)
print("Index of Maximum Value:", max_index) 

Random Array:
 [[369  48 452 430]
 [396 415 188 203]
 [130  38   7 126]
 [184 177 417 337]]
Maximum Value: 452
Index of Maximum Value: (0, 2)


In [145]:
#Find the maximum value and its index in a randomly generated array.
import numpy as np
rand_arr3 = np.random.randint(0, 500, size=(4, 4))
max_value = rand_arr3[0][0]
pos_i, pos_j = 0, 0

print("Array:\n", rand_arr3)

for i in np.arange(4):
    for j in np.arange(4):
        if rand_arr3[i][j] >= max_value:
            max_value = rand_arr3[i][j]
            pos_i, pos_j = i, j

print(f"Maximum Value in the array is: {max_value}")
print(f"Index of Maximum Value is : ({pos_i}, {pos_j})")


Array:
 [[334 329 460 447]
 [ 61 230 493 186]
 [201 200 124 280]
 [ 61 162 233  80]]
Maximum Value in the array is: 493
Index of Maximum Value is : (1, 2)


**End of File**