# Hands-On Exercises

1. Create a 3x3 identity matrix using NumPy.

2. Generate a 2D array with random integers and compute the row-wise sum.

3. Create a 1D array with 10 evenly spaced values between 0 and 100.

4. Perform element-wise addition, multiplication, and division on two random arrays of size 4x4.

5. Find the maximum value and its index in a randomly generated array.

In [7]:
#Create a 3x3 identity matrix using NumPy.
import numpy as np
identity_matrix = np.eye(3)
print(f"Identity Matrix: \n")
print(identity_matrix)

Identity Matrix: 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#Generate a 2D array with random integers and compute the row-wise sum.
rand_arr = np.random.randint(1,20, size=(3, 3))
i = 0
for row in rand_arr:
    print(f"Row Number {i}: {row}") 
    i += 1
print(f"\nRow Sum : {rand_arr.sum(axis =1)}")

Row Number 0: [ 2  1 13]
Row Number 1: [11  6  1]
Row Number 2: [18 19  9]

Row Sum : [16 18 46]


In [11]:
#Create a 1D array with 10 evenly spaced values between 0 and 100.
arr_1D = np.arange(0,100, 10)
print(f"1D Array with 10 evenly spaced values between 0 and 100 :\n")
print(arr_1D)

1D Array with 10 evenly spaced values between 0 and 100 :

[ 0 10 20 30 40 50 60 70 80 90]


In [13]:
#Perform element-wise addition, multiplication, and division on two random arrays of size 4x4.
rand_arr1 = np.random.randint(10,30, size=(4, 4))
rand_arr2 = np.random.randint(30,40, size=(4, 4))

print("\nRandom Array 1:\n", rand_arr1)
print("\nRandom Array 2:\n", rand_arr2)

#element-wise addition
elem_addition = rand_arr1 + rand_arr2
print(f"\nResult of element-wise addition:\n {elem_addition}")

#element-wise multiplication
elem_multiplication = np.dot(rand_arr1, rand_arr2)
print(f"\nResult of element-wise multiplcation:\n {elem_multiplication}")

#element-wise division
elem_division = np.divide(rand_arr1, rand_arr2)
print(f"\nResult of element-wise division:\n {elem_division}")


Random Array 1:
 [[17 28 17 23]
 [18 28 26 12]
 [16 17 23 26]
 [19 18 27 13]]

Random Array 2:
 [[31 32 39 31]
 [33 32 35 30]
 [39 31 39 31]
 [35 31 32 39]]

Result of element-wise addition:
 [[48 60 56 54]
 [51 60 61 42]
 [55 48 62 57]
 [54 49 59 52]]

Result of element-wise multiplcation:
 [[2919 2680 3042 2791]
 [2916 2650 3080 2672]
 [2864 2575 2948 2733]
 [2691 2424 2840 2473]]

Result of element-wise division:
 [[0.5483871  0.875      0.43589744 0.74193548]
 [0.54545455 0.875      0.74285714 0.4       ]
 [0.41025641 0.5483871  0.58974359 0.83870968]
 [0.54285714 0.58064516 0.84375    0.33333333]]


In [17]:
#Find the maximum value and its index in a randomly generated array.
import numpy as np
rand_arr3 = np.random.randint(0, 500, size=(4, 4))
max_value = rand_arr3[0][0]
pos_i, pos_j = 0, 0

print("Array:\n", rand_arr3)

for i in np.arange(4):
    for j in np.arange(4):
        if rand_arr3[i][j] >= max_value:
            max_value = rand_arr3[i][j]
            pos_i, pos_j = i, j

print(f"Maximum Value in the array is: {max_value}")
print(f"Index of Maximum Value is : ({pos_i}, {pos_j})")


Array:
 [[ 57  34 128 168]
 [ 78 332 453 238]
 [426 276 434 370]
 [460 391 173 144]]
Maximum Value in the array is: 460
Index of Maximum Value is : (3, 0)
